wx:
  appID: wx641d56d264861f30
  appsecret: 7c081de02365220207eab607558c4ebd
  templateId: 4I8SZQQHMhAregBqicPiPtOEj_ewdoG3zEXrLeEHPZQ
# 和风天气https://dev.qweather.com/
hefeng:
  key: d332be52028a442e9e164a25782b931f
  publicID: HE2209212037071926
tx:
  key: HX3BZ-XMQC3-C2E3M-3AKB4-MP2IS-U4FAZ
  SK: s2CApGqdtPtpU7lx6LSAJ8rs3Z5yYS
tianxin:
  key: b1b6ab8b1a70497ca6a024f50075373
server:
  port: 80
logging:
  level:
    root: info
    cn.simon.controller: debug